graphicsmagick under the hood except for psd files and imagemagick's convert -flatten
aic-collections/aicdams-lakeshore pull request #340
Opened 2017-01-12 23:09 UTC by jenlindner

2017-01-12 23:19 UTC, scossu commented
What is the issue with gm and `convert -flatten`?

2017-01-13 02:06 UTC, jenlindner commented
It's because gm uses mogrify to do those operations by default, but doesn't
support the -flatten argument. Another way around it is to use gm's convert
for the same thing:

https://github.com/minimagick/minimagick/issues/392

It seems worthwhile and I started working on a test for that today too.

Jen

On Thu, Jan 12, 2017 at 5:19 PM, Stefano Cossu <notifications@github.com>
wrote:

> What is the issue with gm and convert -flatten?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/aic-collections/aicdams-lakeshore/pull/340#issuecomment-272315191>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AALYVP5bMx9I_ObIuK6km9XfsHRpXQ5Cks5rRrUBgaJpZM4LiWLs>
> .
>

2017-01-14 20:31 UTC, awead requested changes

2017-01-14 20:31 UTC, awead commented on app/models/file_set.rb
> +      # byebug
remove.

2017-01-14 20:31 UTC, awead commented on app/models/file_set.rb
> +        end
why not:
``` ruby
when *image_mime_types_with_cli
  MiniMagick.with_cli(:imagemagick) do
    Hydra::Derivatives::ImageDerivatives.create(filename, outputs: image_outputs)
  end
when *self.class.image_mime_types
  Hydra::Derivatives::ImageDerivatives.create(filename, outputs: image_outputs)
[...]

def image_mime_types_with_cli
  ["psd", "vnd.adobe.photoshop"]
end
```
This makes the method less branchy. Alternatively, you could define `image_mime_types_with_cli` in config/initializers/hydra_works.rb if you need to use these mime types outside of this class.

2017-01-14 20:31 UTC, awead commented on spec/models/file_set/file_set_derivatives_spec.rb
> +        before {
use do/end with multilines. {} are reserved for one-liners.

2017-01-16 14:03 UTC, jenlindner commented on app/models/file_set.rb
> +        end
Yes, cleaner.

2017-01-16 14:03 UTC, jenlindner commented on spec/models/file_set/file_set_derivatives_spec.rb
> +        before {
Right.

2017-01-18 01:38 UTC, awead approved these changes

2017-01-18 01:39 UTC, merged