Universal Viewer Dist and RIIIF and IIIF Manifest files
aic-collections/aicdams-lakeshore pull request #373
Opened 2017-05-05 21:58 UTC by jenlindner

2017-05-06 02:34 UTC, scossu commented
Just to be clear, this is not a candidate for merging into 1.1.0. There is still some testing to be done.

2017-05-06 15:31 UTC, awead commented
Note. Don't merge this until after 1.1.0 is released.

2017-05-08 21:17 UTC, awead requested changes
@jenlindner looks good overall. It needs a rebase off of develop first, and then let's talk about the remaining bits.

2017-05-08 21:17 UTC, awead commented on app/assets/stylesheets/viewer.scss
> +    // position: absolute;
can you remove the iframe if this is commented-out?

2017-05-08 21:17 UTC, awead commented on app/controllers/curation_concerns/generic_works_controller.rb
> +  # overriding CC show action to render the html template for assets that uses the layout specific to universal viewer which occupies all columns, no sidebar
This comment should be moved down so that it's right about `def show`. Also, could you explain what specific line or lines in the method you're overriding? I'm wondering that if you're changing the template or view code, you could change the template or just override the view code instead of the controller code.

2017-05-08 21:17 UTC, awead commented on Gemfile
> +gem 'openseadragon', '0.3.0'
openseadragon is already included in line 17

2017-05-08 21:17 UTC, awead commented on app/models/file_set.rb
> +    def image_mime_types
We shouldn't need this. It's in `config/initializers/hydra_works.rb`

2017-05-08 21:17 UTC, awead commented on app/models/solr_document.rb
> +  module Hydra::Works::MimeTypes::ClassMethods
Hmm. I'm wondering why this is needed here. It's been overridden in `config/initializers/hydra_works.rb`

2017-05-08 21:17 UTC, awead commented on app/presenters/aic_work_show_presenter.rb
> +    'a brief yet clear description'
This seems like a good candidate for an entry in the locales file!

2017-05-08 21:17 UTC, awead commented on app/presenters/aic_work_show_presenter.rb
> +class AICWorkShowPresenter < Sufia::WorkShowPresenter
You've defined a new class here but it only has one subclass, so why the inheritance?

2017-05-08 21:17 UTC, awead commented on app/presenters/asset_presenter.rb
> +class AssetPresenter < AICWorkShowPresenter
AssetPresenter is the only class inheriting from AICWorkShowPresenter, so I would merge the two classes and put the methods in AICWorkShowPresenter in this class.

2017-05-08 21:17 UTC, awead commented on app/presenters/concerns/displays_image.rb
> +    return nil unless FileSet.exists?(id)
This is hitting Fedora and we shouldn't do that in a presenter context. Run the solr query here and reutrn nil if the query is nil.

2017-05-08 21:17 UTC, awead commented on app/presenters/concerns/displays_image.rb
> +    width = doc["response"]["docs"][0]["width_is"]
You build a SolrDocument here:
``` ruby
hit = ActiveFedora::SolrService.query("id:#{id}")
doc = SolrDocument.new(hit)
```
Now, you can call `doc.height` and `doc.width`
see: https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/solr_service.rb#L47

2017-05-08 21:17 UTC, awead commented on app/renderers/universal_viewer.rb
> +  include Singleton
Is UniversalViewer supposed to be a singleton? Why? I've heard singletons are "bad" just curious...

2017-05-08 21:17 UTC, awead commented on app/services/iiif_authorization_service.rb
> +class IIIFAuthorizationService
Could put some class-level documentation in here? I'm guessing this is something that `Riif` uses? A service that takes a controller as a param caught me off-guard.

2017-05-08 21:17 UTC, awead commented on app/views/curation_concerns/base/show_asset.html.erb
> +<% provide :page_title, @presenter.page_title %>
Could add some comments to indicate what line(s) are being overridden?

2017-05-08 21:17 UTC, awead commented on config/secrets.yml
> -  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
I would revert this change. It isn't germane to the PR, and the key should be indented.

2017-05-08 21:17 UTC, awead commented on app/services/manifest_service.rb
> +    builder = IIIFManifest::ManifestFactory.new(@presenter)
I think the better approach here is to create your own factory:
``` ruby
class PdfManifestFactory < IIIFManifest::ManifestFactory
  def add_media_sequences(manifest, media_info)
    [...]
end
```
But, isn't `manifest` above just `self.to_h`?

2017-05-08 21:17 UTC, awead commented on spec/spec_helper.rb
> +def in_travis?
use https://github.com/aic-collections/aicdams-lakeshore/blob/master/spec/support/lakeshore_testing.rb#L31 instead

2017-05-19 18:30 UTC, jenlindner commented on app/presenters/aic_work_show_presenter.rb
> +    'a brief yet clear description'
@awead a brief yet clear entry! working on it now :-)

2017-05-19 20:30 UTC, jenlindner commented on app/views/curation_concerns/base/show_asset.html.erb
> +<% provide :page_title, @presenter.page_title %>
They're added, at line 15.

2017-05-19 20:33 UTC, jenlindner commented on app/services/manifest_service.rb
> +    builder = IIIFManifest::ManifestFactory.new(@presenter)
This is the main aspect I couldn't quite get, I tried in a variety of ways to make this work with its own factory. I don't think this is the worst way for the time being. And to_h is a method in the factory that adds an awful lot of behavior, isn't just the to_hash one might expect.

2017-05-19 20:35 UTC, jenlindner commented on app/renderers/universal_viewer.rb
> +  include Singleton
This is another thing I took pretty much without any questions from Hyku, so couldn't really answer. We could ask Trey or Justin if you'd like, though.

2017-05-19 22:00 UTC, jenlindner commented
hi @awead, I have a question. There's caching happening on the rails side that prevents the viewer from loading a good portion of the time. I've experimented some this afternoon with different types of headers to force expiration with no luck, but a little more research turned up turbolinks as a likely culprit too. Does that sound plausible to you? I started looking into ways to leave them enabled for everything except the controller and action in question, but thought I'd ask for your feedback as well. Thanks.

2017-05-20 14:33 UTC, awead commented
@jenlindner yes, that seems very likely. We could disable it altogether, if needed, but maybe there's a subtler way. Have you asked @jcoyne or others involved with Hyku?

2017-05-21 15:50 UTC, jenlindner commented
Okay, I tested with turbolinks disabled site-wide and the problem disappears. Yay to finding the root cause.

So then, as to how to disable them only in this view: one way is to use a data attribute in link tags, but our code doesn't use an html link tag to load the viewer, and the viewer generates its own html. Another, which I think might be the way to go, is to put "data-no-turbolink" into the body tag, which I think might best be accomplished in a layout. (I'm getting information on disabling them from this post: http://blog.flightswithfriends.com/post/53943440505/how-to-disable-turbolinks-in-rails-4)

We use the Curation Concerns layout code on the show pages: 

https://github.com/projecthydra/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/curation_concern_controller.rb#L9-L10

https://github.com/projecthydra/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/themed_layout_controller.rb#L13-L21

This creates the body tag: https://github.com/projecthydra/curation_concerns/blob/master/app/views/layouts/curation_concerns.html.erb#L1

So, one option is to override this layout in LAKE to add the attribute to the body tag.

Another option might be to override the method with_themed_layout(view_name = nil) in LAKE to take a parameter for adding an attribute to the body tag. 

Do you have any recommendations, @awead @jcoyne?

2017-05-23 00:49 UTC, awead commented
@jenlindner I've seen `data-no-turbolink` before as an option. Does that fix the problem? If not, I'd say post to hydra-tech about this and see what Hyku is doing, otherwise I think we'd just have to nix turbolinks.

2017-05-26 17:21 UTC, jenlindner commented
That does fix the problem, thanks @awead. I added it to a new layout, added the layout to the generic works controller and added a controller test that checks for both the new template and the layout in the show action.

2017-06-29 15:05 UTC, awead approved these changes

2017-07-01 00:34 UTC, merged